@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Produto {
- codigo interno unico
- descricao curta
- descricao extensa
- descricao tecnica
- conjunto de fotos
- marca
- referencia
- codigo de barras
- codigo de producao
- preço unitário tabela s/ impostos
- quantidade
}

class Categoria{
- codigo alfanumerico
- descricao
}

class Armazem{
- planta
}

class AreaDeArmazenamento{
- corredor
- fila
- prateleira
}

class Compartimento{}

class Caixa{
- tamanho
}

class Catalogo{}

class Cliente{
- nome
- identificado valido IVA
- email
- numero Telefonico
- data de nascimento
- sexo
- endereço(s) cobrança
- endereço(s) entrega
- identificador unico
}

class PedidoDeProdutos{
- identificador numerico
- data/hora registo
- morada de faturação
- morada de entrega
- produto encomendado
- metodo de envio
- metodo de pagamento
}

class Carrinho{
-Lista de produtos
}

class Rastreamento{
- estado
}

class Questionário {
- texto livre
- escolha multipla
- ordenação/ranking
}

class AGV{
- identificador
- breve descrição
- modelo
- peso máximo que pode transportar
- autonomia
- localização base
- tarefa
}

class Tarefa{
-estado
}

class VendedorParceiro{}

class Rota{}

class LocalizacaoBase {}



AGV "1--*" -- "1" Armazem : opera >
AGV "1" -- "1--*" Produto : coleta >
AGV "1" -- "1--*" Tarefa : coleta >
AGV "1" -- "1--*" Rota : tem >
AGV "1" -- "1--*" LocalizacaoBase : tem >

Armazem "1" -- "1--*" AreaDeArmazenamento : contém >
Armazem "1" -- "1--*" LocalizacaoBase : contém >

AreaDeArmazenamento "1" -- "1--*" Caixa : contem >
AreaDeArmazenamento "1" -- "1--*" Compartimento : contem >

Carrinho "1" -- "1" PedidoDeProdutos : corresponde >

Catalogo "1" -- "1--*" Categoria : contém >

Cliente "1" -- "1" Carrinho : efetua >
Cliente "1" -- "1" Questionário : realiza >

Compartimento "1" -- "1" Produto : contém >

PedidoDeProdutos "1" -- "1--*" Produto : contém >
PedidoDeProdutos "1" -- "1" Rastreamento : >
PedidoDeProdutos "1" -- "1" Cliente : refere-se a >
PedidoDeProdutos "1" -- "1--*" Tarefa : compreende >

Produto "1" -- "1" Categoria : pertence >
Produto "1" -- "1" Armazem : provém >
Produto "1" -- "1" VendedorParceiro : provém >

@enduml
