@startuml

autonumber
actor "Client" as C
participant AddProductToShoppingCarUI as UI <<presentation>>
participant AddProductToShoppingCarController as Controller <<application>>
participant ViewProductCatalogUI as ui <<presentation>>
database ProductRepository as repository <<repository>>
database ClientRepository as rep <<repository>>

participant "Product" as Domain <<domain>>
participant PersistenceContext as Persistence <<persistence>>
participant RepositoryFactory as Factory <<factory>>
database ProductOrderRepository as Repository <<repository>>

activate C
C -> UI : Inicia o processo de adicionar um produto \n ao seu carrinho de compras
activate UI
UI --> C : Mostra o catálogo de produtos
deactivate UI
C -> UI : Escolhe o produto pretendido
activate UI
UI --> C : Solicita a quantidade relativa ao produto
deactivate UI
C -> UI : Informa a quantidade
activate UI
UI --> C : Apresenta os dados e solicita a confirmação
deactivate UI
C -> UI : Confirma os dados
activate UI

UI --> C : Informa o sucesso da operação
deactivate UI
deactivate C



@enduml