@startuml

autonumber
actor "Client" as C
participant ResponderQuestionarioUI as UI <<presentation>>

activate C
C -> UI : Inicia o processo de responder a um questionário
activate UI
UI --> C : Mostra os questionários que existem por responder
deactivate UI
C -> UI : Seleciona o questionário que pretende responder
activate UI
UI --> C : Mostra a informação inicial do questionário
loop enquanto existirem perguntas a serem feitas
UI --> C : Mostra a pergunta do questionário
deactivate UI
C -> UI : Responde à pergunta apresentada
activate UI
end
UI --> C : Mostra a informação final do questionário
UI --> C : Informa o sucesso da operação
deactivate UI
deactivate C

@enduml