@startuml
'https://plantuml.com/class-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0
skinparam classBackgroundColor beige
skinparam ArrowColor #222222

package "<<aggregate>> Product" {
    entity Product
    class Photos
    class UniqueInternalCode
    class Categoria
}

entity Product <<entity>> <<root>> {
    -<<VO>> ShortDescription
    -<<VO>> ExtendedDescription
    -<<VO>> TechnicalDescription
    -<<VO>> descricao tecnica
    -<<VO>> conjunto de photos
    -<<VO>> marca
    -<<VO>> referencia
    -<<VO>> codigo de barras
    -<<VO>> codigo de producao
    -<<VO>> preço unitário tabela s/ impostos
    -<<VO>> quantidade

}

class Photos {}

class UniqueInternalCode <<value object>>

class Categoria{
- codigo alfanumerico
- descricao
}

class Armazem{
- planta
}

class AreaDeArmazenamento{
- corredor
- fila
- prateleira
}

class Compartimento{}

class Caixa{
- tamanho
}

class Catalogo{}

class Cliente{
- nome
- identificado valido IVA
- email
- numero Telefonico
- data de nascimento
- sexo
- endereço(s) cobrança
- endereço(s) entrega
- identificador unico
}

class Encomenda{
- identificador numerico
- data/hora registo
- morada de faturação
- morada de entrega
- produto encomendado
- metodo de envio
- metodo de pagamento
}

class Carrinho{
-Lista de produtos
}

class Rastreamento{
- estado
}

class Questionário {
- texto livre
- escolha multipla
- ordenação/ranking
}

class AGV{
- identificador
- breve descrição
- modelo
- peso máximo que pode transportar
- autonomia
- localização base
- tarefa
}

class Tarefa{
-estado
}

class VendedorParceiro{}

class Rota{}

class LocalizacaoBase {}

AGV -- "1--*" Product : coleta >
AGV -- "1--*" Tarefa : coleta >
AGV -- "1--*" Rota : tem >
AGV -- "1--*" LocalizacaoBase : tem >

Armazem -- "1--*" AreaDeArmazenamento : contém >
Armazem -- "1--*" LocalizacaoBase : contém >

AreaDeArmazenamento -- "1--*" Caixa : contem >
AreaDeArmazenamento -- "1--*" Compartimento : contem >

Carrinho -- "1" Encomenda : corresponde >

Catalogo -- "1--*" Categoria : contém >

Cliente -- "1" Carrinho : efetua >
Cliente -- "1" Questionário : realiza >

Compartimento -- "1" Product : contém >

Encomenda -- "1--*" Product : contém >
Encomenda -- "1" Rastreamento : >
Encomenda -- "1" Cliente : refere-se a >
Encomenda -- "1--*" Tarefa : compreende >

Product --> "1" UniqueInternalCode : has

Product -- "1" Categoria : pertence >
Product -- "1" VendedorParceiro : provém >

@enduml
