@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Project Manager" as M
participant System as S
autonumber

activate M
M -> S : start the control system of AGV
activate S

S --> M : responds
deactivate S

@enduml